# Generated by Django 5.2.6 on 2025-10-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_imagen360_delete_panorama'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen360',
        ),
    ]
