# Generated by Django 5.2.6 on 2025-10-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0003_delete_imagen360'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre descriptivo de la imagen 360', max_length=200, verbose_name='Título')),
                ('imagen', models.ImageField(help_text='Sube una imagen equirectangular (panorámica 360). Ratio recomendado 2:1', upload_to='imagenes_360/', verbose_name='Imagen 360')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la imagen', verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Solo se mostrará la imagen marcada como activa en la página principal', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Imagen 360',
                'verbose_name_plural': 'Imágenes 360',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
