# Generated by Django 5.2.6 on 2025-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono_menu', models.ImageField(help_text='Imagen para el botón que abre el menú (recomendado: 200x200px)', upload_to='config/', verbose_name='Icono del menú principal')),
                ('color_fondo', models.CharField(default='#667eea', help_text='Color hexadecimal para el fondo del botón (ej: #667eea)', max_length=7, verbose_name='Color de fondo')),
                ('activo', models.BooleanField(default=True, help_text='Mostrar u ocultar el menú en la página', verbose_name='Menú activo')),
            ],
            options={
                'verbose_name': 'Configuración del Menú',
                'verbose_name_plural': 'Configuración del Menú',
            },
        ),
        migrations.CreateModel(
            name='Escena360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Nombre de la escena (ej: 'Sala Principal', 'Jardín', 'Terraza')", max_length=200, verbose_name='Título')),
                ('imagen', models.ImageField(help_text='Imagen equirectangular para esta escena. Ratio recomendado 2:1', upload_to='imagenes_360/', verbose_name='Imagen 360')),
                ('icono', models.ImageField(help_text='Imagen circular para el botón del menú (recomendado: 200x200px)', upload_to='iconos_360/', verbose_name='Icono del botón')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la escena', verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el menú (menor número = más a la izquierda)', verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, help_text='Si está desactivada, no aparecerá en el menú', verbose_name='Activa')),
                ('es_principal', models.BooleanField(default=False, help_text='La escena que se muestra al cargar la página', verbose_name='Escena principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Escena 360',
                'verbose_name_plural': 'Escenas 360',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.DeleteModel(
            name='Imagen360',
        ),
    ]
