# Generated by Django 5.2.6 on 2025-10-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_configuracionmenu_escena360_delete_imagen360'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEscena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Nombre de la categoría (ej: 'Planta Baja', 'Primer Piso', 'Exteriores')", max_length=200, verbose_name='Título')),
                ('icono', models.ImageField(help_text='Imagen circular para el botón principal (recomendado: 200x200px)', upload_to='categorias/', verbose_name='Icono del botón principal')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el menú (menor número = más a la izquierda)', verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, help_text='Si está desactivada, no aparecerá en el menú', verbose_name='Activa')),
                ('color_fondo', models.CharField(default='#667eea', help_text='Color hexadecimal para el botón (ej: #667eea)', max_length=7, verbose_name='Color de fondo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Escenas',
                'verbose_name_plural': 'Categorías de Escenas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionMenu',
        ),
        migrations.AlterModelOptions(
            name='escena360',
            options={'ordering': ['categoria__orden', 'orden', 'titulo'], 'verbose_name': 'Escena 360', 'verbose_name_plural': 'Escenas 360'},
        ),
        migrations.RemoveField(
            model_name='escena360',
            name='es_principal',
        ),
        migrations.AlterField(
            model_name='escena360',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='icono',
            field=models.ImageField(help_text='Imagen circular para el botón secundario (recomendado: 200x200px)', upload_to='iconos_360/', verbose_name='Icono del botón'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden dentro de su categoría', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='titulo',
            field=models.CharField(help_text="Nombre de la escena (ej: 'Sala Principal', 'Jardín')", max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='escena360',
            name='categoria',
            field=models.ForeignKey(default=1, help_text='Botón principal al que pertenece esta escena', on_delete=django.db.models.deletion.CASCADE, related_name='escenas', to='cms.categoriaescena', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
