# Generated by Django 5.2.6 on 2025-10-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_categoriaescena_delete_configuracionmenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaescena',
            name='imagen_fondo',
            field=models.ImageField(default=1, help_text='Imagen 360 que se mostrará como fondo al seleccionar esta categoría', upload_to='fondos_categorias/', verbose_name='Imagen 360 de fondo'),
            preserve_default=False,
        ),
    ]
