# Generated by Django 5.2.6 on 2025-10-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_categoriaescena_imagen_fondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoCreador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del creador o institución', max_length=200, verbose_name='Nombre')),
                ('logo', models.ImageField(help_text='Logo del creador (recomendado: fondo transparente, max 150px de alto)', upload_to='logos/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, help_text='Enlace opcional al sitio web del creador', verbose_name='URL')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor número = más a la izquierda)', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logo Creador',
                'verbose_name_plural': 'Logos Creadores',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='categoriaescena',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen 360 que se mostrará como fondo al seleccionar esta categoría', null=True, upload_to='fondos_categorias/', verbose_name='Imagen 360 de fondo'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción que se mostrará en la parte izquierda de la pantalla', verbose_name='Descripción'),
        ),
    ]
