# Generated by Django 5.2.6 on 2025-10-14 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_logocreador_alter_categoriaescena_imagen_fondo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInterfaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usar_imagen_descripcion', models.BooleanField(default=False, help_text='Si está activado, se usará la imagen en lugar del color', verbose_name='Usar imagen de fondo en descripción')),
                ('imagen_fondo_descripcion', models.ImageField(blank=True, help_text='Imagen de fondo para el panel de descripción lateral', null=True, upload_to='config/', verbose_name='Imagen de fondo para descripción')),
                ('color_descripcion', models.CharField(default='#ffffff', help_text='Color hexadecimal (ej: #ffffff para blanco)', max_length=7, verbose_name='Color de fondo descripción')),
                ('transparencia_descripcion', models.IntegerField(default=95, help_text='0 = transparente, 100 = opaco', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Transparencia descripción (%)')),
                ('color_logos', models.CharField(default='#ffffff', help_text='Color hexadecimal (ej: #ffffff para blanco)', max_length=7, verbose_name='Color de fondo logos')),
                ('transparencia_logos', models.IntegerField(default=90, help_text='0 = transparente, 100 = opaco', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Transparencia logos (%)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Interfaz',
                'verbose_name_plural': 'Configuración de Interfaz',
            },
        ),
    ]
