# Generated by Django 5.2.6 on 2025-10-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_configuracioninterfaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='mostrar_fondo_logos',
            field=models.BooleanField(default=True, help_text='Si está desactivado, los logos no tendrán ningún fondo', verbose_name='Mostrar fondo en logos'),
        ),
    ]
