# Generated by Django 5.2.6 on 2025-10-15 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_configuracioninterfaz_mostrar_fondo_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='fuente_texto_descripcion',
            field=models.CharField(choices=[('Arial, sans-serif', 'Arial'), ('Helvetica, sans-serif', 'Helvetica'), ('Georgia, serif', 'Georgia'), ('Times New Roman, serif', 'Times New Roman'), ('Courier New, monospace', 'Courier New'), ('Verdana, sans-serif', 'Verdana'), ('Trebuchet MS, sans-serif', 'Trebuchet MS'), ('Impact, sans-serif', 'Impact'), ('Comic Sans MS, cursive', 'Comic Sans MS'), ('Palatino, serif', 'Palatino'), ('-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', 'Sistema (Recomendado)')], default='-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', help_text='Tipografía para el texto de la descripción', max_length=100, verbose_name='Fuente del texto'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='fuente_titulo_descripcion',
            field=models.CharField(choices=[('Arial, sans-serif', 'Arial'), ('Helvetica, sans-serif', 'Helvetica'), ('Georgia, serif', 'Georgia'), ('Times New Roman, serif', 'Times New Roman'), ('Courier New, monospace', 'Courier New'), ('Verdana, sans-serif', 'Verdana'), ('Trebuchet MS, sans-serif', 'Trebuchet MS'), ('Impact, sans-serif', 'Impact'), ('Comic Sans MS, cursive', 'Comic Sans MS'), ('Palatino, serif', 'Palatino'), ('-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', 'Sistema (Recomendado)')], default='-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', help_text='Tipografía para el título de la descripción', max_length=100, verbose_name='Fuente del título'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='tamano_texto_descripcion',
            field=models.IntegerField(default=16, help_text='Tamaño de letra del texto en píxeles', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(48)], verbose_name='Tamaño del texto (px)'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='tamano_titulo_descripcion',
            field=models.IntegerField(default=24, help_text='Tamaño de letra del título en píxeles', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(72)], verbose_name='Tamaño del título (px)'),
        ),
    ]
