# Generated by Django 5.2.6 on 2025-10-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_configuracioninterfaz_fuente_texto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='titulo_principal',
            field=models.CharField(default='Visor 360', help_text='Título fijo que aparece en la parte superior de todas las páginas', max_length=200, verbose_name='Título Principal'),
        ),
    ]
