# Generated by Django 5.2.6 on 2025-10-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_configuracioninterfaz_titulo_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='mostrar_titulos',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no se mostrarán los títulos en la parte superior', verbose_name='Mostrar títulos superiores'),
        ),
    ]
