# Generated by Django 5.2.6 on 2025-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_configuracioninterfaz_mostrar_titulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioninterfaz',
            name='mostrar_titulos',
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='mostrar_fondo_titulos',
            field=models.BooleanField(default=True, help_text='Si está desactivado, los títulos no tendrán ningún fondo', verbose_name='Mostrar fondo en títulos'),
        ),
    ]
