# Generated by Django 5.2.6 on 2025-10-15 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_remove_configuracioninterfaz_mostrar_titulos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaescena',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'Categoría de Escena', 'verbose_name_plural': 'Categorías de Escenas'},
        ),
        migrations.AlterModelOptions(
            name='escena360',
            options={'ordering': ['categoria', 'orden', 'titulo'], 'verbose_name': 'Escena 360', 'verbose_name_plural': 'Escenas 360'},
        ),
        migrations.AlterModelOptions(
            name='logocreador',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Logo de Creador', 'verbose_name_plural': 'Logos de Creadores'},
        ),
        migrations.RemoveField(
            model_name='categoriaescena',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='tamano_titulo_principal',
            field=models.IntegerField(default=32, help_text='Tamaño de letra del título principal en píxeles', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(72)], verbose_name='Tamaño del título principal (px)'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='tamano_titulo_secundario',
            field=models.IntegerField(default=22, help_text='Tamaño de letra del título de la escena actual en píxeles', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(48)], verbose_name='Tamaño del título secundario (px)'),
        ),
        migrations.AlterField(
            model_name='categoriaescena',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Categoría activa'),
        ),
        migrations.AlterField(
            model_name='categoriaescena',
            name='color_fondo',
            field=models.CharField(default='#ffffff', help_text='Color hexadecimal (ej: #ffffff para blanco)', max_length=7, verbose_name='Color de fondo'),
        ),
        migrations.AlterField(
            model_name='categoriaescena',
            name='icono',
            field=models.ImageField(upload_to='categorias/', verbose_name='Icono de la categoría'),
        ),
        migrations.AlterField(
            model_name='categoriaescena',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen que se mostrará al seleccionar esta categoría (opcional)', null=True, upload_to='categorias/', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='categoriaescena',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='categoriaescena',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título de la categoría'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Escena activa'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenas', to='cms.categoriaescena', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='icono',
            field=models.ImageField(upload_to='iconos/', verbose_name='Icono de la escena'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='imagen',
            field=models.ImageField(upload_to='escenas/', verbose_name='Imagen 360'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='escena360',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título de la escena'),
        ),
        migrations.AlterField(
            model_name='logocreador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Logo activo'),
        ),
        migrations.AlterField(
            model_name='logocreador',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='logocreador',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del creador'),
        ),
        migrations.AlterField(
            model_name='logocreador',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='logocreador',
            name='url',
            field=models.URLField(blank=True, help_text='Enlace al hacer clic en el logo', verbose_name='URL (opcional)'),
        ),
    ]
