# Generated by Django 5.2.6 on 2025-10-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_categoriaescena_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escena360',
            name='video_youtube',
            field=models.URLField(blank=True, help_text='URL del video de YouTube (ej: https://www.youtube.com/watch?v=VIDEO_ID)', verbose_name='Video de YouTube (opcional)'),
        ),
    ]
